version: '2'
services:
  browser:
    image: jkonowitch/chrome-38:latest
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    command: ["/wait-for-it.sh", "novnc:6000", "--", "/start-chrome.sh"]
    shm_size: 1g
    volumes:
      - chrome-user-data:/chrome-user-data
    extra_hosts:
      - local-tv.onepeloton.com:host-gateway
    networks:
      - x11
  novnc:
    image: theasp/novnc:latest
    environment:
      - RUN_XTERM=no
      # Adjust screen size
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:
volumes:
  chrome-user-data: